PREFIX sg: <http://www.springernature.com/scigraph/ontologies/core/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sgg: <http://www.springernature.com/scigraph/graphs/>
construct {
?s ?p ?o
}
where {
    graph sgg:articles.content-hub{
        ?s rdf:type sg:Article .
        ?s sg:title ?t .
        ?s sg:hasFieldOfResearchCode []
        filter (regex(?t,'Palaeozoic'))
        filter (regex(?t,'osteichthyan'))
        ?s ?p ?o
    }
}