```
PREFIX sg: <http://www.springernature.com/scigraph/ontologies/core/>
PREFIX sgg: <http://www.springernature.com/scigraph/graphs/>
describe ?s
where {
    ?s a sg:Article .
    ?s sg:title ?t .
    filter (regex(?t, 'Palaeozoic'))
    filter (regex(?t, 'osteichthyan'))
}
```
