PREFIX sg: <http://www.springernature.com/scigraph/ontologies/core/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sgg: <http://www.springernature.com/scigraph/graphs/>

describe ?s ?be
where {
        ?s a sg:Book .
    	?s sg:isbn "978-0-230-50307-6" .
    	?s sg:hasBookEdition ?be .
}