PREFIX sg: <http://www.springernature.com/scigraph/ontologies/core/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sgg: <http://www.springernature.com/scigraph/graphs/>

describe ?s ?a
where {
    	?s a sg:Grant .
} limit 1