PREFIX sg: <http://www.springernature.com/scigraph/ontologies/core/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sgg: <http://www.springernature.com/scigraph/graphs/>

describe ?s ?be
where {
        ?s a sg:Book .
    	?s sg:hasBookEdition ?be .
    	?be sg:title "Gothic and the Comic Turn"
}