PREFIX sg: <http://www.springernature.com/scigraph/ontologies/core/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sgg: <http://www.springernature.com/scigraph/graphs/>

construct
{
    ?s ?p ?o .
    ?j 	?p_ ?o_ .
}
where {
        ?s a sg:JournalBrand .
        ?s sg:title "Nature" .
    	?s ?p ?o .
        ?j sg:hasJournalBrand ?s .
    	?j a sg:Journal .
    	?j ?p_ ?o_ .
}