prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix onto: <http://www.ontotext.com/>
prefix sg: <http://www.springernature.com/scigraph/ontologies/core/>

construct {
  ?s ?p ?o
}
# from onto:explicit
where {
  bind ("978-0-230-50307-6" as ?isbn)
  {
    ?b a sg:Book ; sg:isbn ?isbn .
    bind (?b as ?s)
    ?s ?p ?o .
  }
  union
  {
    ?b a sg:Book ; sg:isbn ?isbn .
    ?b ^sg:hasBook ?bc .
    bind (?bc as ?s)
    ?s ?p ?o .
    filter (?p = rdf:type)
  }
}
