prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix onto: <http://www.ontotext.com/>
prefix sg: <http://www.springernature.com/scigraph/ontologies/core/>

construct {
  ?s ?p ?o
}
# from onto:explicit
where {
  bind ("10.1038/nature13195" as ?doi)
  {
    ?a a sg:Article ; sg:doi ?doi .
    bind (?a as ?s)
    ?s ?p ?o .
  }
  union
  {
    ?a a sg:Article ; sg:doi ?doi .
    ?a sg:hasContribution ?c .
    bind (?c as ?s)
    ?s ?p ?o .
  }
  union
  {
    ?a a sg:Article ; sg:doi ?doi .
    ?a sg:hasContribution/sg:hasAffiliation ?af .
    bind (?af as ?s)
    ?s ?p ?o .
  }
}
