prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix onto: <http://www.ontotext.com/>
prefix sg: <http://www.springernature.com/scigraph/ontologies/core/>

construct {
  ?s ?p ?o
}
# from onto:explicit
where {
  bind ("Nature" as ?title)
  {
    ?jb a sg:JournalBrand ; sg:title ?title .
    bind (?jb as ?s)
    ?s ?p ?o .
  }
  union
  {
    ?jb a sg:JournalBrand ; sg:title ?title .
    bind (?jb as ?s)
    ?j a sg:Journal .
    ?j sg:hasJournalBrand ?jb .
    bind (?j as ?s)
    ?s ?p ?o .
  }
}
